"""Add journal entries table

Revision ID: 55994fcd310e
Revises: e90b5a879cc7
Create Date: 2026-01-23 00:09:36.258704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55994fcd310e'
down_revision = 'e90b5a879cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
